POST http://localhost:3003/api/pictures
Content-Type: application/json
Authorization: Bearer 


{
    "url": "https://images.pexels.com/photos/2333855/pexels-photo-2333855.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "title": "Decoration",
    "description": "Pretty big lamps"
}